### ISSUE TITLE
Package history?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/cchecks#10]
If I follow correctly, using `cch_pkgs()` one cannot get the history for packages? Could there be another function or an argument `history` to give access to `https://cranchecks.info/pkgs/{package}/history`?

**Comment by sckott** [comment]
yes, will do. i assume this is a dup of #13 ?

**Comment by sckott** [comment]
or is #13 about `/history/:date`  ?

**Comment by maelle** [comment]
Yeah the other issue is about the other endpoint. 

In the docs website btw I added cross-references between package history and history across all packages.

**Comment by sckott** [comment]
ok

**Comment by maelle** [comment]
I think you closed the wrong issue?

Now there's a function for `https://cranchecks.info/pkgs/{package}/history` but not for `/history/:date`?

**Comment by sckott** [comment]
woops, sorry. I will do the `/history/:date` fxn today and close this one

**Comment by maelle** [comment]
No problem, it _is_ confusing (but necessary) to have the two history things :grin:
