### ISSUE TITLE
List rules for a package

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/cchecks#14]
Whilst writing examples in the docs I realized I was expecting 

* `cchn_pkg_rule_list()` to filter rules for the package at hand, 

* `cchn_rule_list()` to have a package name argument to filter rules for a package.

Would that make sense?

**Comment by maelle** [comment]
Why are there these two functions btw, why not only one whose path is "." by default, and if there's no DESCRIPTION, behave like `cchn_rule_list`?

**Comment by sckott** [comment]
agree it makes sense for the `cchn_pkg*` fxn to list rules for the current pkg where its run from. i'll add that

i wanted to have separate fxns to make it clear one handles email and pkg name input and one does not - and that makes the code simpler to maintain for me :)
