### ISSUE TITLE
Not all CRAN Note fields are picked up

### ISSUE THREAD

**Issue by mpadge** [ropenscilabs/cchecks#19]
One of my packages ([`dodgr`](https://cran.r-project.org/package=dodgr)) currently generates 3 Notes:
``` r
library(foghorn)
pkg <- "dodgr"
cran_details(pkg = pkg)
#> # A tibble: 3 x 7
#>   package version result check     flavors           n_flavors message          
#>   <chr>   <chr>   <chr>  <chr>     <chr>                 <dbl> <chr>            
#> 1 dodgr   0.2.7   NOTE   for GNU … r-devel-linux-x8…        12 "     GNU make i…
#> 2 dodgr   0.2.7   NOTE   installe… r-devel-linux-x8…         7 "     installed …
#> 3 dodgr   0.2.7   NOTE   dependen… r-devel-linux-x8…         5 "     Namespace …
```

and yet:
``` r 
library(cchecks)
x <- cch_pkgs_history (x = pkg)
h <- x$data$history$check_details # main data.frame of check results
table (data.frame (output = h$output,
                   n_flavors = vapply (h$flavors, length, integer (1))))
#>                                    n_flavors
#> output                               4  7  9 11 12
#>   GNU make is a SystemRequirements.  1  1  1  2 25
```

<sup>Created on 2020-06-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

All Notes are picked up by `foghorn`, yet only one of them appears on `cranchecks.info`. The one that is picked up is the first ("GNU Make is a SystemRequirements"), while the missing ones are the "installed package size" Note, and the "dependencies in R code" check which yields a "Namespace in Imports field not imported from" Note. This pattern is general - all packages with multiple Note fields only have the first one in the `cranchecks` data.

**Comment by sckott** [comment]
Thanks Mark. That is indeed a problem

**Comment by sckott** [comment]
fixed in API, but will have to make changes to cch_pkgs_history probably for the next month while there's two different data structures

**Comment by sckott** [comment]
in two weeks the last 30 days of data will all have same structure :)
