### ISSUE TITLE
rest of copy-pasting

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/cchecks#2]
There are mentions of IUCN in the docs

* https://github.com/ropenscilabs/cchecks/blob/a93a5e5eecd9cb25f94174bba42cd422c2055979/man-roxygen/all.R#L1

* https://github.com/ropenscilabs/cchecks/blob/a93a5e5eecd9cb25f94174bba42cd422c2055979/R/cchecks-package.R#L3

**Comment by sckott** [comment]
thanks, fixed
