### ISSUE TITLE
Failing to register

### ISSUE THREAD

**Issue by pat-s** [ropenscilabs/cchecks#20]
I somehow cannot manage to register via `cchecks::cchn_register()` with v0.1.8.94

```r
cchecks::cchn_register(email = <mail>)
Check your emails for the CRAN checks token
Token: <input token from mail>

Error in self$config$config[["local_size"]] && !self$valid_size_checks(self$config$config[["local_size"]]) : 
  'length(x) = 64 > 1' in coercion to 'logical(1)'
Backtrace:
1: self$valid_size()
2: self$is_conventional()
3: self$local$valid()
4: x$valid()
5: valid_email(email)
6: cchn_register(email, token)
7: interactive_validate_email(email, token, ...)
8: cchecks::cchn_register(email = <mail>)
```

In addition some suggestions:

- A message stating to wait a few seconds until the email arrives and then pasting the token into the R console.
- An info whether the token should be pasted plain or in quotes

**Comment by sckott** [comment]
thanks, is the email address the one on your github profile?

**Comment by pat-s** [comment]
Yes

**Comment by sckott** [comment]
The error is in the dependency https://github.com/ropenscilabs/addressable - I can't seem to replicate the error with your email address. 

So that error comes from calling exactly this: `cchecks::cchn_register(email = <your mail>)` Or did you not namespace the function call?

**Comment by sckott** [comment]
You're in the user database. Did you try it again with success?

**Comment by pat-s** [comment]
> Or did you not namespace the function call?

When facing the issue I did not namespace it, I loaded the package before.

I just tried again (just namespacing the call) and can reproduce the issue.
Could it be that the error is thrown because I am already in the user database?

**Comment by sckott** [comment]
> Could it be that the error is thrown because I am already in the user database? 

not the error you showed above as thats from the email address validation step before any http requests to the API. 

If you make a registration request for an email that already exists it should give:

```r
email 'foo@bar.com' already registered
Token added for ‘foo@bar.com’
```

**Comment by pat-s** [comment]
Ok. I definitely do not get `email 'foo@bar.com' already registered` for my GH email, just tried again. Maybe that helps :)

**Comment by sckott** [comment]
Did those two things about the messages given on running the register function. 

Changed email validation step, try again after reinstalling if you can. I deleted your email/token from the database. To get a new one, go to that file with cached email/tokens and delete the line with the email in question and save the file. I added that bit to the docs for the function in the last commit.

**Comment by pat-s** [comment]
Thanks. Registered again and it works now :)

**Comment by sckott** [comment]
thanks for sticking with this despite the problems
