### ISSUE TITLE
can not use reprex

### ISSUE THREAD

**Issue by yonicd** [ropenscilabs/cchecks#9]
``` r
library(cchecks)
cchn_register('yonicd@gmail.com')
#> Error in cchn_register("yonicd@gmail.com"): No email or no token and not in interactive mode
details::details(sessioninfo::session_info(),summary = 'session info')
```

<details closed>

<summary> <span title="Click to Expand"> session info </span> </summary>

``` r

─ Session info ───────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       macOS Catalina 10.15.4      
 system   x86_64, darwin15.6.0        
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2020-05-08                  

─ Packages ───────────────────────────────────────────────────────────────────
 package     * version  date       lib source        
 assertthat    0.2.1    2019-03-21 [1] CRAN (R 3.6.0)
 backports     1.1.6    2020-04-05 [1] CRAN (R 3.6.2)
 cchecks     * 0.1.4.91 2020-05-08 [1] local         
 cli           2.0.2    2020-02-28 [1] CRAN (R 3.6.0)
 clipr         0.7.0    2019-07-23 [1] CRAN (R 3.6.0)
 crayon        1.3.4    2017-09-16 [1] CRAN (R 3.6.0)
 crul          0.9.0    2019-11-06 [1] CRAN (R 3.6.0)
 curl          4.3      2019-12-02 [1] CRAN (R 3.6.0)
 desc          1.2.0    2018-05-01 [1] CRAN (R 3.6.0)
 details       0.2.2    2020-04-30 [1] local         
 digest        0.6.25   2020-02-23 [1] CRAN (R 3.6.0)
 evaluate      0.14     2019-05-28 [1] CRAN (R 3.6.0)
 fansi         0.4.1    2020-01-08 [1] CRAN (R 3.6.0)
 glue          1.4.0    2020-04-03 [1] CRAN (R 3.6.2)
 highr         0.8      2019-03-20 [1] CRAN (R 3.6.0)
 htmltools     0.4.0    2019-10-04 [1] CRAN (R 3.6.0)
 httpcode      0.3.0    2020-04-10 [1] CRAN (R 3.6.2)
 httr          1.4.1    2019-08-05 [1] CRAN (R 3.6.0)
 jsonlite      1.6.1    2020-02-02 [1] CRAN (R 3.6.0)
 knitr         1.28     2020-02-06 [1] CRAN (R 3.6.0)
 magrittr      1.5      2014-11-22 [1] CRAN (R 3.6.0)
 png           0.1-7    2013-12-03 [1] CRAN (R 3.6.0)
 R6            2.4.1    2019-11-12 [1] CRAN (R 3.6.0)
 Rcpp          1.0.4.6  2020-04-09 [1] CRAN (R 3.6.3)
 rematch       1.0.1    2016-04-21 [1] CRAN (R 3.6.0)
 rlang         0.4.6    2020-05-02 [1] CRAN (R 3.6.2)
 rmarkdown     2.1      2020-01-20 [1] CRAN (R 3.6.0)
 rprojroot     1.3-2    2018-01-03 [1] CRAN (R 3.6.0)
 sessioninfo   1.1.1    2018-11-05 [1] CRAN (R 3.6.0)
 stringi       1.4.6    2020-02-17 [1] CRAN (R 3.6.0)
 stringr       1.4.0    2019-02-10 [1] CRAN (R 3.6.0)
 whoami        1.3.0    2019-03-19 [1] CRAN (R 3.6.0)
 withr         2.2.0    2020-04-20 [1] CRAN (R 3.6.2)
 xfun          0.13     2020-04-13 [1] CRAN (R 3.6.2)
 xml2          1.3.1    2020-04-09 [1] CRAN (R 3.6.2)
 yaml          2.2.1    2020-02-01 [1] CRAN (R 3.6.0)

[1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

</details>

<br>

<sup>Created on 2020-05-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by sckott** [comment]
thanks @yonicd i'm not sure I follow though. the report is that you can't use reprex with this pkg?

**Comment by yonicd** [comment]
correct

**Comment by sckott** [comment]
ah

**Comment by sckott** [comment]
any ideas on this @maelle `rhub::validate_email` (what `cchn_register` is based on) uses the same setup where it stops if no email or no token, and is not interactive. my first reaction is that maybe reprex can't handle these cases? i've not used reprex much, and I can't find anything about interactive mode vs not interactive with reprex

**Comment by gaborcsardi** [comment]
@yonicd In your reprex, you can read out the token from an environment variable, and then `cchn_register()` should not ask for it. (I don't know if it does, but if it has the email and the token, then I guess it does not need to, right?)

Then you will have to tell to whoever is rep(roducing) the ex(ample) that they also need to set up this environment variable before.

**Comment by yonicd** [comment]
Hi

which ENV var?

I don't see in the function which ENV var it is looking for

```r
function(email = NULL, token = NULL, ...) {
  if (is.null(email) || is.null(token)) {
    if (!interactive()) {
      stop("No email or no token and not in interactive mode")
    }
    return(interactive_validate_email(email, token, ...))
  }
  add_token(email, token)
  message("Token added for ", sQuote(email))
  cat("\n")
}
```

**Comment by gaborcsardi** [comment]
> which ENV var?

Any env var you want. E.g. your reprex is:

```r
library(cchecks)
cchn_register('yonicd@gmail.com', token = Sys.getenv("MYTOKEN")
```

and you tell people to set `MYTOKEN`.

**Comment by gaborcsardi** [comment]
In general, how do you expect reprex to work if the code needs a password or other sensitive information? You don't want to share the password I suppose? Without the password how could people run your code?

**Comment by yonicd** [comment]
Thanks for the guidance. 

I'm just testing this repo for @sckott. 

I do not know what ENV VAR he is pulling from.

**Comment by sckott** [comment]
thanks for the help @gaborcsardi !  

I don't think this is about the token really, it's more about can reprex handle interactive only behavior? i assume not?

I think the solution here generally for any function that has a route that only works if `interactive() == TRUE` and wants to use reprex is to avoid the interactive only route. Unless reprex has a way to allow interactive behavior?

**Comment by gaborcsardi** [comment]
reprex runs in a non-interactive subprocess, so no, no interactive behavior is allowed. 

I thought that your function does not need interaction if all arguments are specified.

**Comment by sckott** [comment]
> I thought that your function does not need interaction if all arguments are specified.

correct, at the top he only specified 1 of 2 params though :)  to avoid the interactive route, users have to supply both email and token, just like `rhub::validate_email`

i think there's nothing left to do here, reprex can not handle interactive mode, which is fine. 

And @yonicd , the emails and tokens are stored in `file.path(rappdirs::user_data_dir("cranchecks", "cchecks"), "emails.csv")` - similar to how rhub does it. so no env vars are used.
